site_name: Spring Persistent Tasks
site_url: https://spring-persistent-task.sterl.org
site_description: A lightweight task management framework for Spring Boot with JPA persistence, clustering support, and retry mechanisms for asynchronous task execution
site_author: Paul Sterl
use_directory_urls: false

# SEO and Social Media
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/sterlp/spring-persistent-tasks
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  generator: false

theme:
    name: material
    language: en
    palette:
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
    features:
      - content.code.copy
      - content.code.annotate
      - navigation.indexes
      - navigation.path
      - navigation.prune
      - navigation.expand
      - navigation.top
      - search.suggest
      - search.highlight
      - toc.follow

plugins:
  - search:
      lang: en
      separator: '[\s\-\.]+'
  - tags:
      tags_file: tags.md
  - glightbox
  - awesome-pages
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - toc:
      permalink: true
      title: On this page
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

repo_url: https://github.com/sterlp/spring-persistent-tasks
repo_name: sterlp/spring-persistent-tasks
edit_uri: edit/main/doc/docs/

# Copyright
copyright: Copyright &copy; 2024 Paul Sterl - Licensed under MIT License