site_name: Spring Persistent Tasks
site_url: https://spring-persistent-task.sterl.org
theme:
    name: material
    features:
      - content.code.copy
      - content.code.annotate
      - navigation.indexes
      - navigation.path
      - navigation.prune
      - navigation.expand

plugins:
  - search
  - tags
  - glightbox
  - awesome-nav

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc