site_name: Spring Persistent Tasks
theme:
    name: material
    features:
      - content.code.copy
      - content.code.annotate
plugins:
  - search
  - sitemap:
      site_url: https://spring-persistent-task.sterl.org
  - tags
  - glightbox
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc
repo_url: https://github.com/sterlp/spring-persistent-tasks