spring:
  jpa:
    generate-ddl: true
    open-in-view: false
  datasource:
    hikari:
      maximum-pool-size: 200
org:
  jobrunr:
    background-job-server:
      enabled: true
      
logging:
  level:
    org.sterl.spring.task: debug
