spring:
  application:
    name: example
  jpa:
    open-in-view: false

  persistent-tasks:
    scheduler-enabled: true
    
springdoc:
  swagger-ui:
    use-root-path: true

logging:
  level:
    org.sterl.spring.persistent_tasks: DEBUG