spring:
  application:
    name: example
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

  persistent-tasks:
    max-threads: 1

  liquibase:
      change-log: classpath:db/changelog/db.changelog-master.xml

management:
  endpoints:
    web:
      exposure:
        include: '*'
  appoptics:
    metrics:
      export:
        enabled: true
      
springdoc:
  swagger-ui:
    use-root-path: true

logging:
  level:
    org.sterl.spring.persistent_tasks: DEBUG