name: Java CI with Maven

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Node 22
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'npm'
        cache-dependency-path: ui/package-lock.json
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: PMD with Maven
      run: mvn pmd:pmd --file pom.xml

    - name: Deploy Nexus
      if: ${{ github.ref == 'refs/heads/main' }}
      run: mvn -B source:jar deploy --file pom.xml -DskipTests
      env:
        MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
